[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "7ff919019714f44ebd24d7de9ec3a7950ca0a4d6"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "95cedb27235f0e9f738c627db8677ad99e0760ac119de6c9713b81a8c1e57f81"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "7ff919019714f44ebd24d7de9ec3a7950ca0a4d6"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "e798868ca61595aea2685f51ba0935788d3d702281e1f6c57e3cd3ff0ae3bb4a"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "7ff919019714f44ebd24d7de9ec3a7950ca0a4d6"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "602c6ecaad6f4db32818f13b00bfa9efc42c4594d574a7533f35123e878e3580"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "7ff919019714f44ebd24d7de9ec3a7950ca0a4d6"
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "f97e6465062a3fd1a3dc0b6de290be2371d5e6474e646feb25af9148faca2e20"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "7ff919019714f44ebd24d7de9ec3a7950ca0a4d6"
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "6f149a3ab8e0eeff474e6266e3099bc56c21a455ff9a64cf5d3670ce491fe35e"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"

[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "281b8876f555349fabfae683584ad1df14353dd2"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "f2ae51efd24351a910c57ab1ee9c7db1dbef5729449e49e79456335c7fccb535"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-build_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "281b8876f555349fabfae683584ad1df14353dd2"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "6225384498eece598b0760d0feb860343998559e183c47d11b7e98bf8875b514"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-build_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "281b8876f555349fabfae683584ad1df14353dd2"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "385a32658f21dd26665b30582d1ef80beb6adf44dd6e43d22da9bd703fece532"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-build_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "281b8876f555349fabfae683584ad1df14353dd2"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "4f596e49f19ecd9258074e1c61eeca351fe3de5334976ed3f7610f86feca7bc8"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-build_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "281b8876f555349fabfae683584ad1df14353dd2"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "f725820dd330d880a2745d5dccd90b7a5b10f719e297f087115ee1eff4b04bcc"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-build_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"

[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a3f65d94e525acafebad36f4dd7e921b08edb84e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "cf71c26ea63501d1901e69d75ba1271e774ed4549cdd1c84603f21e322427bf6"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-extract_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a3f65d94e525acafebad36f4dd7e921b08edb84e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "69dcab83dde8bd26e44ca82ccc0a2ccfd87c193461e6d75fa0ee5325de99fd1d"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-extract_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a3f65d94e525acafebad36f4dd7e921b08edb84e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "7ad5855e3a10bb7c89f70eed122e5b5d655eae8c4c3f51f27e4d8228b3765a23"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-extract_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a3f65d94e525acafebad36f4dd7e921b08edb84e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "a5b3698b8487b9a1d3b04dbef2dfb86d09ebfd1517910af9bbbf2860e7b37649"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-extract_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a3f65d94e525acafebad36f4dd7e921b08edb84e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "803740d428b0164cd54e52c634a1de94fd66f7ff771303a67eb13ca496f3a9ba"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.4.1-GCCBoostrap/GCCBootstrap-extract_log-v9.4.1-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"
