[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "f8beea01c14ec9b2a82f2c24dbac6db872a4eb80"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "56b8260c20502acee88489f519fdb35355858fd036750e1824ca235818b8e2a9"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "f8beea01c14ec9b2a82f2c24dbac6db872a4eb80"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "d1ed5f7099b76863520d001909efa179443dcc5c0a5fd2c56f40f687102b2642"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "f8beea01c14ec9b2a82f2c24dbac6db872a4eb80"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "53c30286ab7267e2613a006bc0d5f9cf052b3a832f6ff3e1905f509f32754cf7"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "f8beea01c14ec9b2a82f2c24dbac6db872a4eb80"
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "33a2d8574fe8fa22b89d11a71863dd1006e68031b0f7b315965e2421380785ec"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[GCCBootstrap]]
arch = "x86_64"
git-tree-sha1 = "f8beea01c14ec9b2a82f2c24dbac6db872a4eb80"
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap.download]]
    sha256 = "f848d8a7fa9a8ef0631ee9445db9f77181345c921aa82237cf7f72f4498fde3f"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"

[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "a64837c3cc6719f8a116df03761bd0dc8cbb8acf"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "56318b78b35f22e50fc7d8dcab559a8b456710b4f0b2d366c44fe5cc3c2b1c84"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-build_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "a64837c3cc6719f8a116df03761bd0dc8cbb8acf"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "df501ca643d8fc54af4612027f74427fbba452f1cd4b7abd14f8dd7a532b1958"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-build_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "a64837c3cc6719f8a116df03761bd0dc8cbb8acf"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "f140be223fe0b820601662bb9eb8e88315c8c9babcf667bd33276704c55df0ec"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-build_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "a64837c3cc6719f8a116df03761bd0dc8cbb8acf"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "b347441c4fd0a1c33ab8d69f0280ef239367bd9c5473873004758cd7dab7fa0b"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-build_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[GCCBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "a64837c3cc6719f8a116df03761bd0dc8cbb8acf"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-build_log.download]]
    sha256 = "7f667b5e07e4a0624a1756d3c1fc10bff15d2b93391f1f0a282b9cef561120eb"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-build_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"

[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "199a05cd1985055e95c7e118bcc409fcf8f7ab38"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "9077f7a91c257fb0a9bec4dee75d7c5e5a63a7aa61cdefba040ac6b105097599"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-extract_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "199a05cd1985055e95c7e118bcc409fcf8f7ab38"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "3f00ea03236cc5346a00f9ee44627bfc41945903b103240c3c7bc53265ede03f"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-extract_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "199a05cd1985055e95c7e118bcc409fcf8f7ab38"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "3325ae5897b366cb7d409909a74ab4e32ff114caffcc89c8369625c155e84aa2"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-extract_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "199a05cd1985055e95c7e118bcc409fcf8f7ab38"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "3902b80b60ede59172479c9a6e8f0a45ed2be8cfebbc7976f69df8c4bc76a73c"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-extract_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[GCCBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "199a05cd1985055e95c7e118bcc409fcf8f7ab38"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[GCCBootstrap-extract_log.download]]
    sha256 = "d0c96ed6ae27d2326ea6fb8fe872f9559ed1f24c5be201bb6b738cae5df2a330"
    url = "https://github.com/staticfloat/GCCBootstrap_jll.jl/releases/download/v9.0.0-GCCBoostrap/GCCBootstrap-extract_log-v9.0.0-x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"
