# Autogenerated wrapper script for GCCBootstrap_jll for x86_64-w64-mingw32
JLLWrappers.@generate_wrapper_header("GCCBootstrap")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
